alias exal='exa -abghHliS'
alias exa='exa --git --color=always --color-scale --header --long --group --time-style=long-iso --ignore-glob=target'
alias exan='exa --sort=newest'
alias exas='exa --sort=size'
alias exat='exa --tree'
alias ls='exa'
